#!/bin/bash
#
#   gcert - generate Globus certificate from InCommon cert file
#
#   Author:          Brian Vanderwende
#   Last Revised:   17:53, 08 Nov 2022
#

cat << EOF
==========================================================
    NOTICE - GCERT AND GCI HAVE BEEN RETIRED!
==========================================================

As of November 7th, 2022, gcert and gci will no longer
function as CISL has migrated to version 5 of Globus,
which does not use the "myproxy" method of authentication.

You will need to update your unattended workflows to use
the new "guest collection" method. A guest collection can
be configured to provide access to any location on GLADE
or Campaign Storage without two-factor authentication.
(provided you have POSIX access to that path)

See the folllowing documentation for more information on
using guest collections for unattended workflows:

https://arc.ucar.edu/knowledge_base/118521941

EOF

exit 1
