#!/bin/bash
#
#   gci - Globus Campaign Storage interface
#
#   This command redirects actions to other helper commands
#   that perform Globus operations between GLADE and the
#   Campaign Storage file systems
#
#   Author:         Brian Vanderwende
#   Last Revised:   19:02, 21 Mar 2021
#

unset BFILE

function clean_up {
    CMDSTAT=$?
    rm -f $BTMP
    exit $CMDSTAT
}

# Exit upon signal (so we don't resubmit SSH command)
trap clean_up SIGHUP SIGINT SIGQUIT SIGTERM

# Do we need help?
function usage {
cat << EOF
Usage: $0 [OPTIONS] COMMAND

This utility provides a convenient interface for transferring files between
the CISL endpoints "NCAR GLADE" and "NCAR Campaign Storage". An attempt will
be made to auto-authenticate using a long-lived certificate file. All requests
utilize the Globus CLI to schedule and conduct transfers.

Available commands:
    cget    conditionally copy files from campaign Storage to GLADE if newer
    cput    conditionally copy files from GLADE to Campaign Storage if newer
    get     copy files from campaign Storage to GLADE
    put     copy files from GLADE to Campaign Storage
    mkdir   create a new directory on Campaign Storage
    ls      list files from a directory on Campaign Storage
    rm      remove files on Campaign Storage

gci options:
    -b, --background        run transfer in background - do not wait for it to finish
    -f, --force-auth        force gci to re-authenticate endpoints regardless of status
    -l, --cert-lifetime N   authenticate endpoints for N hours (0<N<=720, default=12)

EOF
}

# Set some defaults
export LIFETIME=12 AFORCE=false

while [[ $# -gt 0 ]]; do
    KEY="$1"
    case $KEY in
        -h|--help)
            usage
            exit 0
            ;;
        -b|--background)
            export BGCMD=true
            ;;
        -d|--debug)
            export DEBUG=true
            ;;
        -l|--cert-lifetime)
            if [[ $KEY == *=* ]]; then
                LIFETIME=${KEY#*=}
            else
                LIFETIME=$2
                shift
            fi

            if [[ $LIFETIME < 1 ]] || [[ $LIFETIME > 720 ]]; then
                echo "Error: custom lifetime should be 0 < LIFETIME <= 720 hours"
                exit 200
            fi
            ;;
        -f|--force-auth)
            AFORCE=true
            ;;
        *)
            break
    esac
    shift
done

# If in batch mode, store stdin in a file
if [[ " $@ " == *" --batch "* ]]; then
    MYTMP=${TMPDIR:-fakepath}

    if [[ -d /glade/scratch/$USER ]]; then
        export TMPDIR=/glade/scratch/$USER
    fi
    
    BTMP=$(mktemp ${TMPDIR:-/tmp/}/.gcibatch.XXXXXX)

    # Make sure stdin was actually used
    if [[ $(readlink -f /dev/stdin) =~ /(glade|tmp|$MYTMP)/* ]] ; then
        cat > $BTMP
    fi
fi

# Call main script locally or on login node
export GCIBIN=$(cd "$(dirname "$0")"; pwd)/bin

if [[ $NCAR_HOST == cheyenne ]] && [[ -n $PBS_JOBID ]]; then
    SNODE=$(shuf -i 1-6 -n 1)
    LN=$SNODE SSHSTAT=255
    RCMD="export BGCMD=$BGCMD DEBUG=$DEBUG BTMP=$BTMP TMPDIR=$TMPDIR GCIBIN=$GCIBIN LIFETIME=$LIFETIME AFORCE=$AFORCE; cd $(pwd); $GCIBIN/main $@"

    while [[ $SSHSTAT -eq 255 ]]; do
        ssh cheyenne${LN}.ib0 "/bin/bash -c \"$RCMD\""
        SSHSTAT=$? LN=$((LN + 1))

        if [[ $LN -gt 6 ]]; then
            LN=1
        elif [[ $LN -eq $SNODE ]]; then
            break
        fi
    done

    if [[ $SSHSTAT -eq 255 ]]; then
        echo "Error: could not connect to a login node; transfer aborted"
        exit 255
    fi

    exit $SSHSTAT
else
    $GCIBIN/main $@
fi

clean_up
